### ISSUE TITLE
prog: command not found - when testing argcomplete 1.6.0 from PyPI

### ISSUE THREAD

**Issue by daym** [kislyuk/argcomplete#162]
I'm trying to package argcomplete in the Guix distribution and I get lots of lines like the following lines when testing:

```shell
======================================================================
FAIL: test_unquoted_space (test.TestBash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-argcomplete-1.6.0.drv-0/argcomplete-1.6.0/test/__init__.py", line 758, in test_unquoted_space
    self.assertEqual(self.bash.run_command('prog space f\t'), 'foo bar\r\n')
AssertionError: 'bash: prog: command not found\r\n' != 'foo bar\r\n'
- bash: prog: command not found
+ foo bar
```

Am I missing something?

Also, I've had to rename `test/test.py` to `test/__init__.py` for the tests to run at all. Do I need a special test runner? I've tried nose and pytest so far - no luck.

**Comment by daym** [comment]
With the argcomplete 1.6.0 release on github it does work fine and without any manual renames. Huh.

**Comment by evanunderscore** [comment]
I've been running the tests using `python test/test.py`, but you should also be able to do `python setup.py test`. The Travis job does `coverage run --source=argcomplete ./test/test.py`.

As for why you're seeing that error when trying to run the tests from the sdist - the test program `prog` is not being included because it doesn't have a `.py` extension. We'll either have to add it to MANIFEST.in or give it that extension.

**Comment by evanunderscore** [comment]
I just tried adding the extension and that doesn't seem to be enough to get it included, so I'm not sure exactly how `test.py` makes it in. Perhaps it's easiest to add `include test/*` to MANIFEST.in?
