### ISSUE TITLE
Creating tab completion for Bash script wrapped Python files

### ISSUE THREAD

**Issue by Paebbels** [kislyuk/argcomplete#168]
Hello,

I have a Bash script wrapping a Python script. I have tested argcomplete with my python script and it works. I would like to have the same tab completion for the wrapping Bash script.

**poc.sh:**
```bash
#! /bin/bash
params=$@

# do preload stuff
# - prepare environments
# - acquire license
# - ...

# execute python script
python3 poc.py $params
exitCode=$?

# do unloading stuff
# - release licenses

# return original exit code
exit $exitCode
```

**poc.py:**
```Python
#! /usr/bin/python3
# PYTHON_ARGCOMPLETE_OK
from sys          import path as sys_path
from argcomplete  import autocomplete

sys_path.append("../py")
from PoC import PileOfCores

# entry point
parser = PileOfCores(False, False, False, True, sphinx=True).MainParser
autocomplete(parser)
```

Note: I'm reusing the internal sphinx mode to shorten the execution. Only the parser object is created.

**Is it possible to emit the auto completion rules for `poc.sh` instead of `poc.py`?**

I tried to change the `prog` parameter in the ArgumentParser initializer, but I didn't notice any effects.

**Comment by evanunderscore** [comment]
The global completer examines the file that is being run for the `PYTHON_ARGCOMPLETE_OK` marker. It has no way of knowing that you'll later call through to something that contains it. If you include it in `poc.sh`, it should work.

(If you're trying to do this using `register-python-argcomplete`, you'll need to point it at `poc.sh` instead of `poc.py`.)

**Comment by Paebbels** [comment]
Moving the magic line into the Bash script worked. Thanks.
