### ISSUE TITLE
Improve support for ArgumentParser subclasses

### ISSUE THREAD

**Issue by shx2** [kislyuk/argcomplete#300]
When using argcomplete with a subclass of ArgumentParser, which overrides add_argument() or parse_args(), the subclass methods don't get called when completing.

I believe the problem is in the monkey patching, where this line
`parser.__class__ = type(classname, (IntrospectiveArgumentParser, parser.__class__), {})`
places ArgumentParser in parser's mro before the subclass.

I believe removing ArgumentParser from IntrospectiveArgumentParser's mro would fix the problem (i.e. changing IntrospectiveArgumentParser to be a mixin, which is how it is already being used).

I propose this change:
`class IntrospectiveArgumentParser(ArgumentParser):` --> `class IntrospectiveArgumentParser:`

**Comment by evanunderscore** [comment]
Can you provide some sample code that reproduces the problem you're seeing? The only thing I would expect to break in this instance is if you're overriding `_parse_known_args`, because this is the method IntrospectiveArgumentParser overrides, and it never calls the superclass. For all other methods, the method resolution order should take care of everything, since `parser.__class__` also inherits from ArgumentParser.

**Comment by shx2** [comment]
I tried coming up with sample code, and I think you are correct, and my diagnosys was wrong.
I will open another issue if needed.
Thanks.
