### ISSUE TITLE
TypeError shellcode() given 5 arguments

### ISSUE THREAD

**Issue by soderluk** [kislyuk/argcomplete#316]
When `eval`ing the latest `pipx` autocompletion in `.bashrc` (`eval "$(register-python-argcomplete pipx)"`), I get the following error when starting my terminal:
```
Traceback (most recent call last):
  File "/usr/local/bin/register-python-argcomplete", line 65, in <module>
    args.executable, args.use_defaults, args.shell, args.complete_arguments, args.external_argcomplete_script))
TypeError: shellcode() takes from 1 to 4 positional arguments but 5 were given
```

**Comment by evanunderscore** [comment]
Thanks for the report.

This seems like an environment issue. The fact that `register-python-argcomplete` is itself a Python script used to be an implementation detail, however since moving the script generation into a module inside argcomplete, it now needs to be able to import argcomplete from within that script.

It seems you have multiple versions of argcomplete installed in multiple different environments (either virtual environments, system environments, different versions of Python, etc) and the `register-python-argcomplete` script installed by one version is importing the argcomplete module installed by another, and they are not compatible.

(To be clear, I do consider this a bug in argcomplete, but it's a difficult one to fix, and you'll be much better off trying to fix your environment in the short term.)

**Comment by soderluk** [comment]
@evanunderscore You are correct, I've got a bunch of different envs installed at the moment. I just fixed this to use the correct one with full path.
I thought it would be appropriate to report this, since it might be that others have the same issue.
Thanks for your reply!

**Comment by kislyuk** [comment]
Thanks for reporting. I am going to close this issue since there is nothing actionable on the maintainer side here.
