### ISSUE TITLE
Source tarball for v2.0.0 is different here and at pypi

### ISSUE THREAD

**Issue by mtelka** [kislyuk/argcomplete#384]
I downloaded the sdist tarball from [pypi](https://files.pythonhosted.org/packages/05/f8/67851ae4fe5396ba6868c5d84219b81ea6a5d53991a6853616095c30adc0/argcomplete-2.0.0.tar.gz) and from [github](https://github.com/kislyuk/argcomplete/archive/refs/tags/v2.0.0.tar.gz) and surprisingly after unpacking they differ significantly:

```
$ diff -qr argcomplete-2.0.0-pypi/ argcomplete-2.0.0-github/ 
Only in argcomplete-2.0.0-pypi/: argcomplete.egg-info
Only in argcomplete-2.0.0-github/: common.mk
Only in argcomplete-2.0.0-github/: docs
Only in argcomplete-2.0.0-github/: .github
Only in argcomplete-2.0.0-github/: .gitignore
Only in argcomplete-2.0.0-github/: Makefile
Only in argcomplete-2.0.0-pypi/: PKG-INFO
Files argcomplete-2.0.0-pypi/setup.cfg and argcomplete-2.0.0-github/setup.cfg differ
Only in argcomplete-2.0.0-github/: tox.ini
$
```

The most important differences are the egg-info, `docs`, `PKG-INFO`, and `tox.ini`.  This makes the sdist tarball at pypi hardly usable.  For example, it is not possible to run tests using `tox` there.

**Comment by kislyuk** [comment]
I'm not sure how this is an argcomplete bug. The tarball on github is generated by github while the tarball on PyPI is generated by [build](https://github.com/pypa/build). Also, just to be clear, I don't run the tests using tox and I never committed to supporting tox in the argcomplete API.

I checked and the tarball on PyPI appears to be usable for installing the package from source, which is what it's meant for. Please let me know if you find otherwise, and we can reopen this.
