### ISSUE TITLE
Does argcomplete work for scripts which don't directly invoke the parse?

### ISSUE THREAD

**Issue by sharky93** [kislyuk/argcomplete#96]
For example - a script that instantiates a class from another file which then handles the parsing there.

**Comment by kislyuk** [comment]
Yes, that should work, as long as the `argcomplete.autocomplete(parser)` method is called before the `parser.parse()` method is called.

It helps to understand what happens when argcomplete is activated. From the docs:

Argcomplete gets completions by running your program. It intercepts the execution flow at the moment argcomplete.autocomplete() is called. After sending completions, it exits using exit_method (os._exit by default). This means if your program has any side effects that happen before argcomplete is called, those side effects will happen every time the user presses <TAB> (although anything your program prints to stdout or stderr will be suppressed). For this reason it's best to construct the argument parser and call argcomplete.autocomplete() as early as possible in your execution flow.
